/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.hw4.client;

import java.io.IOException;
import java.util.*;

public class App {
  public static void main(String[] args) throws IOException {
    List<String> xmlList = new ArrayList<>();
    String xml1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<create>\n" +
            "  <account id=\"123456\" balance=\"100000\"/>\n" +
            "  <symbol sym=\"SPY\">\n" +
            "    <account id=\"123456\">1000</account>\n" +
            "  </symbol>\n" +
            "  <symbol sym=\"FB\">\n" +
            "    <account id=\"123456\">1000</account>\n" +
            "  </symbol>\n" +
            "  <symbol sym=\"GOOG\">\n" +
            "    <account id=\"123456\">1000</account>\n" +
            "  </symbol>\n" +
            "</create>";
    xmlList.add(xml1);

    String xml2 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<create>\n" +
            "  <account id=\"12345\" balance=\"100000\"/>\n" +
            "  <symbol sym=\"TLSA\">\n" +
            "    <account id=\"12345\">1000</account>\n" +
            "  </symbol>\n" +
            "  <symbol sym=\"TLSA\">\n" +
            "    <account id=\"12345\">1000</account>\n" +
            "  </symbol>\n" +
            "  <symbol sym=\"TLSA\">\n" +
            "    <account id=\"12345\">1000</account>\n" +
            "  </symbol>\n" +
            "</create>";
    xmlList.add(xml2);

    String xml3 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<create>\n" +
            "  <account id=\"123456\" balance=\"100000\"/>\n" +
            "  <symbol sym=\"TLSA\">\n" +
            "    <account id=\"123456\">10000</account>\n" +
            "  </symbol>\n" +
            "  <account id=\"12345\" balance=\"100000\"/>\n" +
            "  <symbol sym=\"TLSA\">\n" +
            "    <account id=\"12345\">10000</account>\n" +
            "  </symbol>\n" +
            "</create>";
    xmlList.add(xml3);

    String xml4 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <order sym=\"TLSA\" amount=\"100\" limit=\"100\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"100\" limit=\"100\"/>\n" +
            "</transactions>";
    xmlList.add(xml4);

    String xml5 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"12345\">\n" +
            "  <order sym=\"TLSA\" amount=\"-50\" limit=\"95\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"-100\" limit=\"98\"/>\n" +
            "</transactions>";
    xmlList.add(xml5);

    String xml6 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">  \n" +
            "  <query id=\"1084\"/>\n" +
            "  <query id=\"1\"/>\n" +
            "  <query id=\"1085\"/>\n" +
            "  <query id=\"1086\"/>\n" +
            "  <query id=\"1087\"/>\n" +
            "  <cancel id=\"1085\"/>\n" +
            "  <cancel id=\"1086\"/>\n" +
            "  <cancel id=\"1087\"/>\n" +
            "</transactions>";
    xmlList.add(xml6);

    String xml7 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <cancel id=\"721\"/>\n" +
            "</transactions>";
    xmlList.add(xml7);

    String xml8 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <query id=\"715\"/>\n" +
            "  <query id=\"723\"/>\n" +
            "  <query id=\"722\"/>\n" +
            "</transactions>";
    xmlList.add(xml8);

    String xml9 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <query id=\"715\"/>\n" +
            "  <query id=\"723\"/>\n" +
            "  <query id=\"722\"/>\n" +
            "</transactions>";
    xmlList.add(xml9);

    String xml10 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <order sym=\"TLSA\" amount=\"100\" limit=\"100\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"100\" limit=\"101\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"100\" limit=\"102\"/>\n" +
            "</transactions>";
    xmlList.add(xml10);

    String xml11 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"12345\">\n" +
            "  <order sym=\"TLSA\" amount=\"-50\" limit=\"105\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"-100\" limit=\"110\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"-100\" limit=\"110\"/>\n" +
            "</transactions>";
    xmlList.add(xml11);

    String xml12 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"12345\">\n" +
            "  <order sym=\"TLSA\" amount=\"-25\" limit=\"101\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"-25\" limit=\"102\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"-25\" limit=\"101\"/>\n" +
            "</transactions>";
    xmlList.add(xml12);

    String xml13 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <query id=\"715\"/>\n" +
            "  <query id=\"723\"/>\n" +
            "  <query id=\"722\"/>\n" +
            "</transactions>";
    xmlList.add(xml13);

    String xml14 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <query id=\"715\"/>\n" +
            "  <query id=\"723\"/>\n" +
            "  <query id=\"722\"/>\n" +
            "</transactions>";
    xmlList.add(xml14);

    String xml15 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <query id=\"715\"/>\n" +
            "  <query id=\"723\"/>\n" +
            "  <query id=\"722\"/>\n" +
            "</transactions>";
    xmlList.add(xml15);

    String xml16 ="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "</transactions>";
    xmlList.add(xml16);

//    String xml17 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
//            "<transactions id=\"123456\">\n" +
//            "  <order sym=\"SYM\" amount=\"500\" limit=\"33.45\"/>\n" +
//            "  <order sym=\"GOOG\" amount=\"-100\" limit=\"33.45\"/>\n" +
//            "  <order sym=\"FB\" amount=\"100\" limit=\"33.45\"/>\n" +
//            "  <order sym=\"FB\" amont=\"-100\" limit=\"3.45\"/>\n" +
//            "</transactions>";
//    xmlList.add(xml17);

    String xml18 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"123456\">\n" +
            "  <order sym=\"SYM\" amount=\"500\" limit=\"32.45\"/>\n" +
            "  <order sym=\"GOOG\" amount=\"-100\" limit=\"50.45\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"60\" limit=\"103\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"60\" limit=\"118\"/>\n" +
            "</transactions>";
    xmlList.add(xml18);

    String xml19 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<transactions id=\"12345\">\n" +
            "  <order sym=\"TLSA\" amount=\"-30\" limit=\"100\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"-80\" limit=\"105\"/>\n" +
            "  <order sym=\"TLSA\" amount=\"-50\" limit=\"110\"/>\n" +
            "</transactions>";
    xmlList.add(xml19);

    //create
//    for(int i = 0; i < xmlList.size(); i++){
//      te(xmlList.get(i));
//    }
    String xml_test1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<create>\n" +
            "  <account id=\"11\" balance=\"1000\"/>\n" +
            "  <symbol sym=\"SPY\">\n" +
            "    <account id=\"11\">100000</account>\n" +
            "  </symbol>\n" +
            "</create>";
    te(xml_test1);

  }
  public static void te(String xml){
    try{
      Client client = new Client("localhost", 12386);
      System.out.println(xml.length());
      String strlen = Integer.toString(xml.length());
      String newXml = strlen + "\n" + xml;
      client.sendTextMsg(newXml);
      String response = client.receiveTextMsg();
      System.out.println(response);
    }
    catch (Exception e) {
      e.printStackTrace();
    }
  }
}
