/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.hw4.server;

import java.io.IOException;


public class App {
    public static void main(String[] args) throws IOException {
        Server server = new Server(12386); // port# per the requirement
        while (true) {
            server.connectClient();
            System.out.println("Client connected: " + server.getClientSkt().getInetAddress().getHostName());

            // Create a new thread to handle the client
            ClientHandler clientHandler = new ClientHandler(server.getClientSkt());
            Thread clientThread = new Thread(clientHandler);
            clientThread.start();
        }
    }
}
